mcu:
  status:
    inprogress:
      file: .ini
    finished:
      file:
        - .txt
        - .FIN
      key_word: The task is finished.
  tocopy:
    files:
      - .FIN
      - .PDC
      - .txt
      - .REZ
      - .DRZ
  filter:
    regex:
      - '\d+\.\d+\.\d+_\w+$'
      - '\d+\.\d+\.\d+\Z'
      - '\d+_\w+$'
      - '\w+(_|-)\d+\Z'

phits:
  status:
    inprogress:
      file: phits.out
    finished:
      file: phits.out
      key_word: total cpu time
